theme: jekyll-theme-cayman
permalink: /blog/:year/:month/:day/:title
permalink: /about
# title: Dion Niazi
# description: Computer Programer
# author: Dion Niazi
# author_email: dn3gy@virginia.edu
name: Dion Niazi
